"use client";

import type { Metadata } from "next";
import React, { useState } from "react";

import Link from "next/link";
import { usePathname } from "next/navigation";
import clsx from "clsx";

// export const metadata: Metadata = {
//   title: "Next App",
//   description: "Generated by Next.js",
// };

type NavLink = {
  name: string;
  href: string;
};
const navLink = [
  { name: "Register", href: "/register" },
  { name: "Login", href: "/login" },
  { name: "Forgot Password", href: "/forget-password" },
];

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathName = usePathname();

  const [input, setInput] = useState("");

  return (
    <>
      {navLink.map((li: NavLink, i: number) => {
        const checkpathname = li.href || pathName.startsWith(`${li.href}/`);
        console.log(checkpathname, "checkpathname");
        return (
          <Link
            className={
              pathName === (li.href || pathName.startsWith(`${li.href}/`))
                ? "bg-amber-400"
                : "bg-pink-300"
            }
            key={i}
            href={li.href}
          >
            {li.name}
          </Link>
        );
      })}
      <input
        type="text"
        value={input}
        onChange={(e) => setInput(e.target.value)}
      />
      <main className="flex-1">{children}</main>
      <footer className="bg-gray-500 p-4 mt-5">
        <p className="text-white">Copyright 2025</p>
      </footer>
    </>
  );
}
