import type { Metadata } from "next";
import React from "react";
import "../../app/globals.css";

export const metadata: Metadata = {
  title: "Next App 2025",
  description: "Generated by Next.js",
};

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <header
          className="bg-blue-500 p-4
         text-white mb-5"
        >
          <h1 className="text-white text-2xl font-bold">My App111</h1>
        </header>
        <main className="flex-1">{children}</main>
        <footer className="bg-gray-500 p-4 mt-5">
          <p className="text-white">Copyright 2025</p>
        </footer>
      </body>
    </html>
  );
}
